### PR TITLE
New property for sharefile-only users. Story ref: 3228

### PR DESCRIPTION
**Pull request by cmchase**
We can sit on this PR for a bit, but I wanted to get the changes out there

### CODE REVIEW

**Comment by pulczynski** [comment]
:

**Comment by cmchase** [comment]
Retest this please

**Comment by cmchase** [comment]
retest this please

**Comment by cmchase** [comment]
@cpeters, Travis-CI is complaining about Ruby 2.1 and lower with this new property. Any thoughts?

**Pull request merged**
